from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from core.config import settings
from core.database import Base

# Import all models so Alembic sees them for autogenerate
import modules.agent.models       # noqa: F401
import modules.area_intel.models  # noqa: F401
import modules.contracts.models   # noqa: F401
import modules.estimator.models   # noqa: F401
import modules.fraud.models       # noqa: F401
import modules.housing.models     # noqa: F401
import modules.notifications.models  # noqa: F401
import modules.reputation.models   # noqa: F401
import modules.roommate.models    # noqa: F401
import modules.users.models       # noqa: F401

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Override the URL from settings (not alembic.ini) so we never commit credentials
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL_SYNC)

# Objects excluded from autogenerate comparison:
# - indexes: HNSW/GIN/trgm indexes cannot be autogenerated and are managed by SQL migrations
# - foreign_key_constraint: FKs from the baseline schema are managed by init.sql;
#   only NEW FKs added via Alembic migrations are tracked
# New indexes and FKs must be added explicitly in migration upgrade() functions.
def include_object(obj, name, type_, reflected, compare_to):
    if type_ == "index":
        return False  # HNSW/GIN/trgm indexes managed by SQL migrations
    if type_ == "foreign_key_constraint" and reflected and compare_to is None:
        return False  # baseline FKs in DB but not yet in models
    if type_ == "unique_constraint" and reflected and compare_to is None:
        return False  # baseline unique constraints in DB not yet in models
    return True


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
